### ISSUE TITLE
Баланс счёта после пополнения меньше фактического баланса #1

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#1]
# Описание
При пополнении  баланс счёта составляет только сумму пополнения, не учитывая сумму начального баланса до пополнения

# Локализация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L75

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать SavingAccount со следующими параметрами
3. Вставить значение переменной initialBalance = 2_000
4. Вставить значение переменной minBalance = 1_000
5. Вставить значение переменной maxBalance = 10_000
6. Вставить значение переменной rate = 5
7. Вставить сумму пополнения счёта account.add - 3_000

4. Запустить программу
5. Посмотреть на вывод консоли

*Ожидаемый результат:*  баланс счёта после пополнения 5_000 рублей
*Фактический результат:* баланс счёта после пополнения  3_000 рублей
*Тест:* https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L7

# Скриншот
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/1878b341-b1a6-4f8a-9196-0ceb4f467ede)

# Окружение
* **Операционная система:** Windows 10 Pro 22Н2
* **IDE:** IntelliJ IDEA Community Edition 2023.1
* **Java:** OpenJDK 11

**Comment by Feruno** [comment]
Поправил формулу тут https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/5b028d77dad3701bcf330e313fe93aa70b05476f/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L77
