### ISSUE TITLE
Операция расчёта процентов происходит и на положительный баланс

### ISSUE THREAD

**Issue by Feruno** [Feruno/JavaqaTeamDiplom2ABOK#10]
# Описание
Операция расчёта процентов происходит и при положительном балансе.
При положительном балансе при любой ставке ответ должен быть 0.

# Локация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
1. Создать CreditAccount со след параметрами
1. Присвоить initialBalance значение 200.
1. Присвоить creditLimit значение 0.
1. Присвоить rate значение 15.
1. Вызвать метод yearChange.
1. Запустить программу.
1. Посмотреть на вывод консоли.

*Ожидаемый результат :* 0
*Фактический результат :* 30
# Тест https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L137

# Скриншот 
1. Скриншот № 1 
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/9da4988e-6ac3-4fae-a9e9-e48732513aa5)
1. Скриншот № 2
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/3105e68c-6c14-4cc7-9444-f6506a2fc594)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by Veyderian** [comment]
баг исправлен. при положительном балансе процент не начисляется.
