### ISSUE TITLE
не реализован метод  проверки исключений, если минимальный баланс больше максимального

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#11]
# Описание
Не реализован метод проверки исключений IllegalArgumentExeption при некорректных параметрах:
минимальный баланс больше максимального

# Локализация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/5acb5fcf3703ac6505d9cb091707ad59f2314491/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA

2. Создать SavingAccount со следующими параметрами

5. Вставить значение переменной initialBalance = 10_000

6. Вставить значение переменной minBalance = 18_000

7. Вставить значение переменной maxBalance = 11_000

8. Вставить значение переменной rate = 10

9. Запустить программу

10. Посмотреть на вывод консоли

*Ожидаемый результат:* выкидывается исключение вида IllegalArgumentException
*Фактический результат:* AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown
*Тест:*
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/0f686af6e203cb45a5a489a30a44f94f2f345f15/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L304

# Скриншот
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/162068e1-a134-45d2-9114-b8a8613e89c3)

# Окружение
Операционная система: Windows 10 Pro 22Н2
IDE: IntelliJ IDEA Community Edition 2023.1
Java: OpenJDK 11

**Comment by Feruno** [comment]
Исправлено здесь https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a71f6a50ab9d8f5525f0adc9b85369e61de93a80/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L29
