### ISSUE TITLE
не реализован метод проверки исключений, если начальный баланс больше максимального

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#13]
# Описание
Не реализован метод проверки исключений IllegalArgumentExeption при некорректных параметрах:
начальный баланс больше максимального
# Локализация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/5acb5fcf3703ac6505d9cb091707ad59f2314491/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA

2. Создать SavingAccount со следующими параметрами

5. Вставить значение переменной initialBalance = 14_000

6. Вставить значение переменной minBalance = 1_000

7. Вставить значение переменной maxBalance = 10_000

8. Вставить значение переменной rate = 10

9. Запустить программу

10. Посмотреть на вывод консоли

*Ожидаемый результат:* выкидывается исключение вида IllegalArgumentException
*Фактический результат:* AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown
*Тест:*
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/0f686af6e203cb45a5a489a30a44f94f2f345f15/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L318-L332

# Скриншот
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/20968b78-870c-43a0-83c2-f0a7c5b1aac5)

# Окружение
Операционная система: Windows 10 Pro 22Н2
IDE: IntelliJ IDEA Community Edition 2023.1
Java: OpenJDK 11

**Comment by Feruno** [comment]
Исправлено тут 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/1d2a9b254c6cf96baf74ba1e181ad3f740241734/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L39
