### ISSUE TITLE
остаток на счете после оплаты становиться меньше, чем минимальный баланс

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#14]
# Описание
При оплате сумма на счету становиться меньше минимального баланса

# Локализация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/0f686af6e203cb45a5a489a30a44f94f2f345f15/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L46

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать SavingAccount со следующими параметрами
3. Вставить значение переменной initialBalance = 2_000
4. Вставить значение переменной minBalance = 1_000
5. Вставить значение переменной maxBalance = 10_000
6. Вставить значение переменной rate = 5
7. Вставить значение  account.pay(2_000)
8. Запустить программу
9. Посмотреть на вывод консоли

*Ожидаемый результат:*  сумма на  счёте 2_000 рублей
*Фактический результат:* сумма на  счёте 0 рублей
*Тест:* 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/0f686af6e203cb45a5a489a30a44f94f2f345f15/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L116

# Скриншот 1
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/768767f2-e3bb-40cb-a03a-5cd38acd45ff)

# Окружение
* **Операционная система:** Windows 10 Pro 22Н2
* **IDE:** IntelliJ IDEA Community Edition 2023.1
* **Java:** OpenJDK 11

**Comment by Feruno** [comment]
Исправлено тут 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/ec0b5b21adbe5784a01cd48893ab8a986accdb53/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L66
