### ISSUE TITLE
Сумма заявленного максимального баланса не соответствует фактической.  

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#2]
# Описание
При пополнении баланса счёта до суммы равной максимальному балансу происходит ошибка, счёт не пополняется.

# Локализация дефекта

https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L75

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать SavingAccount со следующими параметрами

3. Вставить значение переменной initialBalance = 2_000

4. Вставить значение переменной minBalance = 1_000

5. Вставить значение переменной maxBalance = 10_000

6. Вставить значение переменной rate = 5

7. Вставить сумму пополнения счёта account.add - 8_000

8. Запустить программу

9. Посмотреть на вывод консоли

*Ожидаемый результат:* баланс счёта после пополнения 10_000 рублей
*Фактический результат:* баланс счёта после пополнения 2_000 рублей
*Тест:*
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L55

 
# Скриншот

![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/901b7b31-fe07-47bd-b1d2-9a16d796956c)

# Окружение
* **Операционная система:**  Windows 10 Pro 22Н2
* **IDE:**  IntelliJ IDEA Community Edition 2023.1
* **Java:**  OpenJDK 11

**Comment by Feruno** [comment]
Исправил формулу тут https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/b8ba00ebc9c1f4de7a7d2208ba47286b1bc144f7/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L76C1-L76C1
