### ISSUE TITLE
Лимит кредита может уйти в минус

### ISSUE THREAD

**Issue by Feruno** [Feruno/JavaqaTeamDiplom2ABOK#4]
# Описание
Не обрабатывается возможность ввода отрицательного лимита кредита.

# Локация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L26

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
1. Создать CreditAccount со след параметрами
1. Присвоить initialBalance значение 0.
1. Присвоить creditLimit значение 0.
1. Присвоить rate значение 15.
1. Присвоить в assertThrows creditLimit значение -5 000. 
1. Запустить программу.
1. Посмотреть на вывод консоли.

*Ожидаемый результат :* Выброс исключения.
*Фактический результат :*  Отсутствует выброс исключения.
# Тест 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/928074c0c0140a7767d7af9820d08ea57d1575fe/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L37

# Скриншот 
1. Скриншот № 1 
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/ca088f53-aadd-4bf0-8ea1-97374a359d7c)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by Veyderian** [comment]
Добавлен метод проверки исключений на отрицательный кредитный лимит
