### ISSUE TITLE
Отрицательный баланс при оплате покупки

### ISSUE THREAD

**Issue by Veyderian** [Feruno/JavaqaTeamDiplom2ABOK#5]
# Описание
При оплате баланс счёта уходит в минус, не учитывая ограничения минимального баланса

# Локализация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L50

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA
2. Создать SavingAccount со следующими параметрами
3. Вставить значение переменной initialBalance = 2_000
4. Вставить значение переменной minBalance = 1_000
5. Вставить значение переменной maxBalance = 10_000
6. Вставить значение переменной rate = 5
7. Вставить сумму покупки account.pay - 7_000
8. Запустить программу
9. Посмотреть на вывод консоли

*Ожидаемый результат:*  оплата не прошла, баланс счёта  2_000 рублей
*Фактический результат:* оплата прошла, баланс счёта   -5_000 рублей
*Тест:* 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/4a059787ba9abde0c94bc972a618963674a19ce1/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L91

# Скриншот 1
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/9db2df25-5d9b-42a9-8e76-b3d3409763ee)

# Скриншот 2
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/129328294/30c4e832-be3e-4cd9-b317-96d13317cf67)

# Окружение
* **Операционная система:** Windows 10 Pro 22Н2
* **IDE:** IntelliJ IDEA Community Edition 2023.1
* **Java:** OpenJDK 11

**Comment by Feruno** [comment]
Добавил проверку тут https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/e3c159b9cc2671bd27208bac2b70b319de4f5063/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L50
