### ISSUE TITLE
Нет ограничения на сумму оплаты большую чем лимит кредита. 

### ISSUE THREAD

**Issue by Feruno** [Feruno/JavaqaTeamDiplom2ABOK#6]
# Описание
Нет ограничения на сумму оплаты большую чем лимит кредита. 

# Локация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/066163dcb7a892306412d6c5f6b765e7953bc207/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
1. Создать CreditAccount со след параметрами.
1. Присвоить initialBalance значение 10000.
1. Присвоить creditLimit значение 5_000.
1. Присвоить rate значение 15.
1. Вызвать метод pay c параметром 20000. 
1. Запустить программу.
1. Посмотреть на вывод консоли.

*Ожидаемый результат :* Запрет на операцию, так как сумма превышает лимит кредита (программа должна вернуть false ничего не поменяв на счёте)
*Фактический результат :*  Баланс выходит за рамки лимита
# Тест 
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/54196f596b56887c6059a7e80ac1ba0ce4e54b2b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L62

# Скриншот 
1. Скриншот № 1 
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/41808ad1-3041-4fc6-a5bb-8ddfdf6ba7cd)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by Veyderian** [comment]
баг исправлен, добавлено ограничение на сумму оплаты большую, чем лимит кредита
