### ISSUE TITLE
После операции оплаты баланс на карте становиться отрицательным

### ISSUE THREAD

**Issue by Feruno** [Feruno/JavaqaTeamDiplom2ABOK#7]
# Описание
После операции оплаты сумма на карте  становиться отрицательной, вместо уменьшение баланса на сумму покупки, балансу присваивается отрицательное значение.

# Локация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
1. Создать CreditAccount со след параметрами
1. Присвоить initialBalance значение 1 000.
1. Присвоить creditLimit значение 0.
1. Присвоить rate значение 15.
1. Вызвать метод pay c параметром 999.
1. Запустить программу.
1. Посмотреть на вывод консоли.

*Ожидаемый результат :* Стартовый баланс равен 1
*Фактический результат :*  Стартовый баланс равен -999
# Тест https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L73

# Скриншот 
1. Скриншот № 1 
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/84a24f10-bc65-4542-b4bd-bc9e037205cd)
1. Скриншот № 2
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/c58bf795-0c38-452b-9cf3-9fc81bd83409)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by Veyderian** [comment]
ошибка исправлена. После операции оплаты баланс уменьшается на сумму покупки.

**Comment by Veyderian** [comment]
ошибка исправлена. После операции оплаты баланс уменьшается на сумму покупки.
