### ISSUE TITLE
Вместо пополнения балансу присваиваться новое значение

### ISSUE THREAD

**Issue by Feruno** [Feruno/JavaqaTeamDiplom2ABOK#9]
# Описание
После операции пополнения сумма на карте становиться равна значению на которое пополнили карту.

# Локация дефекта
https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Шаги воспроизведения 
1. Открыть [код программы](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA.
1. Создать CreditAccount со след параметрами
1. Присвоить initialBalance значение 10.
1. Присвоить creditLimit значение 0.
1. Присвоить rate значение 15.
1. Вызвать метод add c параметром 10.
1. Запустить программу.
1. Посмотреть на вывод консоли.

*Ожидаемый результат :* баланс равен 20
*Фактический результат :* баланс равен 10
# Тест https://github.com/Feruno/JavaqaTeamDiplom2ABOK/blob/a316db310234e8775ac388a7af03c848aacb072b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L110

# Скриншот 
1. Скриншот № 1 
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/45fc6d00-4087-4969-b5ee-051aa2ec34c7)
1. Скриншот № 2
![image](https://github.com/Feruno/JavaqaTeamDiplom2ABOK/assets/60847105/36f83574-7bb5-4776-8fef-7895323eb169)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by Veyderian** [comment]
баг исправлен. При пополнении счёта баланс увеличивается на сумму пополнения.
